version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ClientApp"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular/*"
          
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/src/CarMaintenance.Api"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "docker"
    directory: "/ClientApp"
    schedule:
      interval: "weekly"
