export const USER_ROLES = {
  ADMIN: 'admin',
  OWNER: 'owner',
  MECHANIC: 'mechanic',
  VIEWER: 'viewer'
} as const;

export const PERMISSIONS = {
  // Car permissions
  CAR_VIEW: 'car:view',
  CAR_CREATE: 'car:create',
  CAR_EDIT: 'car:edit',
  CAR_DELETE: 'car:delete',
  
  // Maintenance permissions
  MAINTENANCE_VIEW: 'maintenance:view',
  MAINTENANCE_CREATE: 'maintenance:create',
  MAINTENANCE_EDIT: 'maintenance:edit',
  MAINTENANCE_DELETE: 'maintenance:delete',
  MAINTENANCE_APPROVE: 'maintenance:approve',
  
  // Owner permissions
  OWNER_VIEW: 'owner:view',
  OWNER_CREATE: 'owner:create',
  OWNER_EDIT: 'owner:edit',
  OWNER_DELETE: 'owner:delete',
  
  // Admin permissions
  USER_MANAGEMENT: 'user:management',
  SYSTEM_CONFIG: 'system:config',
  ANALYTICS_VIEW: 'analytics:view',
  REPORTS_GENERATE: 'reports:generate',
  
  // Notification permissions
  NOTIFICATION_MANAGE: 'notification:manage'
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [USER_ROLES.ADMIN]: [
    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.CAR_CREATE,
    PERMISSIONS.CAR_EDIT,
    PERMISSIONS.CAR_DELETE,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.MAINTENANCE_DELETE,
    PERMISSIONS.MAINTENANCE_APPROVE,
    PERMISSIONS.OWNER_VIEW,
    PERMISSIONS.OWNER_CREATE,
    PERMISSIONS.OWNER_EDIT,
    PERMISSIONS.OWNER_DELETE,
    PERMISSIONS.USER_MANAGEMENT,
    PERMISSIONS.SYSTEM_CONFIG,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.NOTIFICATION_MANAGE
  ],
  [USER_ROLES.OWNER]: [
    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.CAR_CREATE,
    PERMISSIONS.CAR_EDIT,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.OWNER_VIEW,
    PERMISSIONS.OWNER_EDIT,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_GENERATE
  ],
  [USER_ROLES.MECHANIC]: [
    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_EDIT,
    PERMISSIONS.OWNER_VIEW
  ],
  [USER_ROLES.VIEWER]: [
    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.OWNER_VIEW,
    PERMISSIONS.ANALYTICS_VIEW
  ]
} as const;